project:
  type: website
  output-dir: docs

website:
  title: "EMC Viroscience"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html   # Link to about page, this should not be in posts folder.
  sidebar:
    style: "docked"
    contents:
      - section: "Posts"
        contents:
          - posts/*  # Automatically include all .qmd files in the posts folder in the sidebar
          
format:
  html:
    theme:
      light: jekyll-theme-minimal
      dark: darkly