project:
  type: website
  output-dir: docs

website:
  title: "EMC Viroscience"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
  sidebar:
    style: "docked"
    contents:
      - section: "Posts"
        contents:
          - /*.qmd
          
format:
  html:
    theme:
      light: jekyll-theme-minimal
      dark: darkly